class TestErrors:
    def test(self):
        pass